### ISSUE TITLE
Local video not working on iOS

### ISSUE THREAD

**Issue by rceraline** [Azure/communication-ui-library#1088]
Hi,

We are using callComposite without react. The integration was pretty straightforward but after testing on different devices, we realize that the local video is not working on iPhone or iPad. It works fine on Android. How could we fix this?

Thanks,
Rémi

![image](https://user-images.githubusercontent.com/3820705/141865352-cc554b78-a1f0-4c7d-90dd-c2926bae9f41.png)

**Comment by anjulgarg** [comment]
What version of iOS is your test device using?
We know that versions 15 and greater are experiencing this bug.

**Comment by rceraline** [comment]
Hi @anjulgarg, this test was done on iOS 14.7.1.

**Comment by ddematheu2** [comment]
What browser where you using? (We have limitations on Chrome and Edge). Only Safari support the full set of capabilities.

**Comment by rceraline** [comment]
Hi @ddematheu2, I was using safari.

**Comment by rceraline** [comment]
Any news on this? @anjulgarg @ddematheu2?

**Comment by alcail** [comment]
Thanks for reaching out, @rceraline .
I'm wondering if you could update your package to our latest one and see if it still repro'es.
We fixed a bunched of issues and this one seems to be in it.
We tried to repro your issue on our side but were unable to do it so far with the latest package.
Let us know how it goes.
Thanks

**Comment by rceraline** [comment]
Hi @alcail, 
I did some tests with this package: 1.0.0-alpha-20211120.0011.0.
I have the same problem on iOS. Local video is still not working. Everything is fine on Android.
Was I using the right version?
Thanks

**Comment by alcail** [comment]
Thanks for the update.
The fix was in on the 18th, and we can't seem to repro this issue on our side.
We are still investigating though and will also reach out to the Calling SDK team to see what's happening here.
We'll keep you updated as soon as we have an answer for your issue.

**Comment by anjulgarg** [comment]
@rceraline Did you try the GA version of our library?
Could you confirm if this issue has been fixed?

**Comment by rceraline** [comment]
Hi @anjulgarg, I tested the last version but it didn't work. It was actually worst. I must have used the wrong version.

Here what I did:

1. Fetch the last commit on main ![image](https://user-images.githubusercontent.com/3820705/147832659-c590e811-bead-451d-9af5-30bda3334d04.png)
2. Build the callComposite file in English and French with the command `rush build`. I had to change the rush.json file as my nodejs version was greater than 15. 
![image](https://user-images.githubusercontent.com/3820705/147832718-0f22a2be-33a2-4bda-9c95-c6c631c6c558.png)
3. Add the file in my index.html in the header section.
4. Initialize the call in my angular app.
```
[...]
private async startCall(communication: { userId: string; token: string }) {
  this.callAdapter = await this.callComposite.loadCallComposite(
    {
      groupId: this.appointmentId,
      displayName: this.user.displayName,
      userId: communication.userId,
      token: communication.token,
    },
    document.getElementById('acs-composite'),
    {
      formFactor: this.isMobile ? 'mobile' : 'desktop',
    }
  );
[...]
}
```

4. Test the call. On iOS, the local video was still white and I am actually getting multiple errors on all mobiles (android + iOS)
![error_message](https://user-images.githubusercontent.com/3820705/147832775-32175326-48ab-493d-878d-9e8e6fd452c8.jpg)

I also noticed some missing translations.

Thanks,

**Comment by anjulgarg** [comment]
Hi @rceraline can you confirm if this was fixed with the latest version?

**Comment by alkwa-msft** [comment]
@rceraline my apologies that this is still an issue.

I was wondering if you can share a repo or any videos of what you are seeing. If we don't get any response we will most likely be closing this issue if we are unable to repro or get anything else to continue this investigation.

**Comment by rceraline** [comment]
Hi @anjulgarg and @alkwa-msft!

Thank you for your message. I didn't test the latest version yet. I plan  to do it tomorrow. As soon as it's done I'll get back to you. 

Is the latest version PublicPreview 1.0.1-beta.2? 

Thanks.

**Comment by alkwa-msft** [comment]
I believe that is correct. Thanks for staying engaged with us and we want to help out if we can!

**Comment by rceraline** [comment]
I tested the latest version on iPad and I was getting the same error. It is impossible to even have a call. It works fine on desktop. 

Information on the device I was using:

Device type | Browser |  
Device model | iPad |  
Operating system | iOS 15.1 |  
Browser version | Chrome Mobile iOS 98.0 |

**Comment by rceraline** [comment]
I just updated the iPad to iOS 15.3.1. Now I can have a call but the local video on the iPad is still not working.

**Comment by anjulgarg** [comment]
Hello @rceraline 
We tested the call composite  without react in an iPad running iOS v15.3.0 and were able to run it without any issues. Local video preview is also visible
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/9782747/154753089-9ceb76af-d521-4d7a-b4f3-1665ba62f904.png)

**Comment by rceraline** [comment]
Hi @anjulgarg,

Thank you for your answer. May I have access to some code. It could help comparing with mine.

In the meantime, here is a sample of my code. It is in an Angular project:

1. I load the callComposite file that I compiled as described in my previous comment. I do this to support different languages.
2. I initialize the callAdapter with loadCallComposite method.

Am I doing anything wrong?

```
private async startCall(communication: { userId: string; token: string }) {
    const callComposite = await this.getcallComposite();
    this.callAdapter = await callComposite.loadCallComposite(
      {
        groupId: this.appointmentId,
        displayName: this.user.displayName,
        userId: communication.userId,
        token: communication.token,
      },
      document.getElementById('acs-composite'),
      {
        formFactor: this.isMobile ? 'mobile' : 'desktop',
      }
    );

    this.store.dispatch(updateChatLoading({ isLoading: false }));

    this.callAdapter.onStateChange((state) => {
      if (!this.isConnected && state.call?.state === 'Connected') {
        this.store.dispatch(joinTheCall());
        this.isConnected = true;
      }
    });

    this.callAdapter.on('participantsJoined', () => {
      this.newParticipantAudio.play();
    });

    this.callAdapter.on('callEnded', () => {
      this.leaveTheCall();
      this.isConnected = false;
    });
  }


getcallComposite(): Promise<any> {
    return this.promiseTimeout(
      10000,
      new Promise((resolve) => {
        let callComposite = (window as any).callComposite;
        if (!callComposite) {
          this.appInsightsService.trackTrace(
            'callComposite is undefined. Try loading it...'
          );

          const lang = this.locale.substring(0, 2);
          const callCompositeUrl = `assets/callComposite.${lang}.js`;
          var script = document.createElement('script'),
            head = document.head || document.getElementsByTagName('head')[0];
          script.src = callCompositeUrl;
          script.async = false;

          script.addEventListener('load', () => {
            resolve((window as any).callComposite);
          });

          head.insertBefore(script, head.firstChild);
        }
      })
    );
  }
```

**Comment by anjulgarg** [comment]
While I go through this code, do you mind trying the non-react sample in our github repo in your iPad 
https://github.com/Azure/communication-ui-library/tree/main/samples/StaticHtmlComposites

**Comment by anjulgarg** [comment]
That's the correct one @rceraline

**Comment by rceraline** [comment]
Hi @anjulgarg, I was not able to figure out how to deploy your solution to an Azure app service in order to test on my iPad. Do you have some instructions explaining how I could do this?

**Comment by anjulgarg** [comment]
Hi @rceraline StaticHtmlComposites example relies on a server (in the same directory) too.
You would need to host the StaticHtmlComposites sample and server separately. 
Static html can be hosted on azure using these docs https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website 

You can build and host the server using an azure app service.
https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=windows&pivots=development-environment-vscode

**Comment by rceraline** [comment]
Hi @anjulgarg, thank you for the instructions. Actually, I was wondering if you guys already have this hosted somewhere, it would be easier for me to test. Do you have something like this?

**Comment by anjulgarg** [comment]
We don't have something that's already hosted I am afraid. Might be easier to run this locally and tunnel it via ngrok for testing it in your ipad? @rceraline

**Comment by anjulgarg** [comment]
@rceraline You only need to ngrok the frontend app and not the server.

**Comment by anjulgarg** [comment]
Hi @rceraline, you only need to tunnel the the IP:Port running the frontend code and open it in your ipad.
No need to tunnel the server

**Comment by rceraline** [comment]
Thanks @anjulgarg, I'll try this soon and let you know how it goes.

**Comment by rceraline** [comment]
Hi @anjulgarg, I was finally able to test the sample with ngrok and it is working fine on the ipad. I'll compare my code with the sample to find a solution. Thanks for your help.

**Comment by anjulgarg** [comment]
Awesome @rceraline 
Closing this issue.
Feel free to open another issue if you face any more challenges.
